name: immunophenotyping_webapp
description: "."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.2.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  json_string: ^3.0.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  intl: ^0.19.0
  flutter_fancy_tree_view: ^1.6.0
  list_picker: ^1.1.0
  provider: ^6.1.2
  syncfusion_flutter_pdf: ^27.2.2
  package_info_plus: ^8.3.0
  fluttertoast: ^8.0.9
  
  webapp_utils:
    git:
#    path: ../webapp_lib/webapp_utils
      ref: 0.1.1
      url: git@github.com:tercen/webapp_lib
      path: webapp_utils

  webapp_ui_commons:
#    path: ../webapp_lib/webapp_ui_commons
    git:
      ref: 0.1.1
      url: git@github.com:tercen/webapp_lib
      path: webapp_ui_commons

  webapp_model:
#    path: ../webapp_lib/webapp_model
    git:
      ref: 0.1.1
      url: git@github.com:tercen/webapp_lib
      path: webapp_model

  webapp_components:
#    path: ../webapp_lib/webapp_components
    git:
      ref: 0.1.1
      url: git@github.com:tercen/webapp_lib
      path: webapp_components

  webapp_workflow:
#    path: ../webapp_lib/webapp_workflow
    git:
      ref: 0.1.1
      url: git@github.com:tercen/webapp_lib
      path: webapp_workflow

#  sci_tercen_client:
#    git:
#      ref: 1.8.0
#      url: git@github.com:tercen/sci_tercen_client
#      path: sci_tercen_client
#    path: ../sci_tercen_client/sci_tercen_client

#



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3





  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo.png
    - assets/img/wait.webp
    - assets/img/ppt_icon.jpeg
    - assets/repos.json
    - assets/workflow_settings.json
    - assets/settings_screen_filter.json
    - assets/workflow_steps.json
    - assets/qc_channels.json

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
